# See https://pre-commit.com/ for usage and config

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # general:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude: static/swagger-ui-bundle.js
      # executable files:
      - id: check-executables-have-shebangs
      # other files (markup & docs):
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/myint/autoflake
    rev: v1.6.0
    hooks:
      - id: autoflake

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        files: ^(app|tests)/
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy app tests
        pass_filenames: false
        require_serial: true
        files: ^(app|tests)/
        types_or: [python, pyi]

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-lock
      - id: poetry-check
      - id: poetry-install
