services:
  db:
    image: postgres:16.1-alpine
    environment:
      PGUSER: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      # POSTGRES_EXTENSIONS: pg_trgm
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - type: bind
        source: ./init-schema.sql
        target: /docker-entrypoint-initdb.d/init-schema.sql
    ports:
      - target: 5432
        host_ip: 127.0.0.1
        published: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "test", "-U", "test"]
      start_period: 60s
      interval: 10s
      timeout: 60s
      retries: 5

  alembic:
    profiles:
      - migration
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./alembic
        target: /backend/alembic
      - type: bind
        source: ./alembic.ini
        target: /backend/alembic.ini
    environment:
      postgres_host: db:5432
      postgres_username: test
      postgres_password: test
      postgres_database: test
      postgres_schema: xi_back_2
    entrypoint: sh

  api:
    profiles:
      - app
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - "--reload"
    ports:
      - target: 8000
        host_ip: 127.0.0.1
        published: 5000
    volumes:
      - type: bind
        source: ./app
        target: /backend/app
      - type: bind
        source: ./tests
        target: /backend/tests
      - type: bind
        source: ./community_avatars
        target: /backend/community_avatars
      - type: bind
        source: ./storage
        target: /backend/storage
    environment:
      WATCHFILES_FORCE_POLLING: true
      postgres_username: test
      postgres_password: test
      postgres_database: test
      postgres_schema: xi_back_2
      # postgres_automigrate: false
