"""invitation_creator_and_sortation

Revision ID: 005
Revises: 004
Create Date: 2024-05-25 20:32:07.334066

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        schema="xi_back_2",
    )
    op.add_column(
        "invitations",
        sa.Column(
            "creator_id", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "creator_id", schema="xi_back_2")
    op.drop_column("invitations", "created_at", schema="xi_back_2")
    # ### end Alembic commands ###
