"""shorter_invitation_token

Revision ID: 009
Revises: 008
Create Date: 2024-08-04 21:21:52.258820

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: Union[str, None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # we don't have users yet, so it's fine to just delete data
    op.execute("TRUNCATE TABLE xi_back_2.invitations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invitations",
        "token",
        existing_type=sa.CHAR(length=50),
        type_=sa.CHAR(length=10),
        existing_nullable=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invitations",
        "token",
        existing_type=sa.CHAR(length=10),
        type_=sa.CHAR(length=50),
        existing_nullable=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
