"""post-service

Revision ID: 011
Revises: 010
Create Date: 2024-08-20 14:17:48.194778

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "011"
down_revision: Union[str, None] = "010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_channels")),
        schema="xi_back_2",
    )
    op.drop_constraint(
        "fk_posts_channel_id_channels", "posts", schema="xi_back_2", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_posts_channel_id_post_channels"),
        "posts",
        "post_channels",
        ["channel_id"],
        ["id"],
        source_schema="xi_back_2",
        referent_schema="xi_back_2",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_posts_channel_id_post_channels"),
        "posts",
        schema="xi_back_2",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_posts_channel_id_channels",
        "posts",
        "channels",
        ["channel_id"],
        ["id"],
        source_schema="xi_back_2",
        referent_schema="xi_back_2",
        ondelete="CASCADE",
    )
    op.drop_table("post_channels", schema="xi_back_2")
    # ### end Alembic commands ###
