"""board_channels

Revision ID: 012
Revises: 011
Create Date: 2024-08-20 22:41:09.445318

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "012"
down_revision: Union[str, None] = "011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_channels",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["xi_back_2.channels.id"],
            name=op.f("fk_board_channels_id_channels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_board_channels")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("board_channels", schema="xi_back_2")
    # ### end Alembic commands ###
