"""hokus

Revision ID: 014
Revises: 013
Create Date: 2024-09-14 20:18:15.373182

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: Union[str, None] = "013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hokus",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("access_group_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups.id"],
            name=op.f("fk_hokus_access_group_id_access_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hokus")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hokus", schema="xi_back_2")
    # ### end Alembic commands ###
