"""access-groups

Revision ID: 014
Revises: 013
Create Date: 2024-09-14 20:16:20.622340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: Union[str, None] = "013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind", sa.Enum("BOARD_CHANNEL", name="accessgroupkind"), nullable=False
        ),
        sa.Column("related_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_groups")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_groups", schema="xi_back_2")
    # ### end Alembic commands ###
