"""pinned_messages

Revision ID: 019
Revises: 018
Create Date: 2024-11-24 12:05:52.928236

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "019"
down_revision: Union[str, None] = "018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
        schema="xi_back_2",
    )
    op.drop_index(
        "ix_xi_back_2_messages_created_at", table_name="messages", schema="xi_back_2"
    )
    op.create_index(
        "created_at_sort_index",
        "messages",
        [sa.text("created_at DESC")],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        "pinned_messages_created_at_sort_index",
        "messages",
        [sa.text("created_at DESC")],
        unique=False,
        schema="xi_back_2",
        postgresql_where=sa.text("pinned IS true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "pinned_messages_created_at_sort_index",
        table_name="messages",
        schema="xi_back_2",
        postgresql_where=sa.text("pinned IS true"),
    )
    op.drop_index("created_at_sort_index", table_name="messages", schema="xi_back_2")
    op.create_index(
        "ix_xi_back_2_messages_created_at",
        "messages",
        ["created_at"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("messages", "pinned", schema="xi_back_2")
    # ### end Alembic commands ###
