"""private_files

Revision ID: 022
Revises: 021
Create Date: 2025-01-06 18:33:20.521059

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "022"
down_revision: Union[str, None] = "021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("access_group_id", sa.Uuid(), nullable=True),
        schema="xi_back_2",
    )
    op.create_foreign_key(
        op.f("fk_files_access_group_id_access_groups"),
        "files",
        "access_groups",
        ["access_group_id"],
        ["id"],
        source_schema="xi_back_2",
        referent_schema="xi_back_2",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_files_access_group_id_access_groups"),
        "files",
        schema="xi_back_2",
        type_="foreignkey",
    )
    op.drop_column("files", "access_group_id", schema="xi_back_2")
    # ### end Alembic commands ###
