"""tutor_materials

Revision ID: 025
Revises: 024
Create Date: 2025-04-26 19:52:43.354730

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "025"
down_revision: Union[str, None] = "024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tutor_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind", sa.Enum("NOTE", "BOARD", name="materialkind"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tutor_materials")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tutor_materials", schema="xi_back_2")
    # ### end Alembic commands ###
