"""tutor_subjects

Revision ID: 026
Revises: 025
Create Date: 2025-06-08 16:08:52.264430

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "026"
down_revision: Union[str, None] = "025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tutor_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
        schema="xi_back_2",
    )
    op.create_index(
        "unique_index_subjects_tutor_id_name",
        "subjects",
        ["tutor_id", "name"],
        unique=True,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_index_subjects_tutor_id_name", table_name="subjects", schema="xi_back_2"
    )
    op.drop_table("subjects", schema="xi_back_2")
    # ### end Alembic commands ###
