"""tutor_invitations

Revision ID: 027
Revises: 026
Create Date: 2025-06-15 16:12:01.092842

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "027"
down_revision: Union[str, None] = "026"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tutor_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.CHAR(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tutor_invitations")),
        sa.UniqueConstraint("code", name=op.f("uq_tutor_invitations_code")),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_tutor_invitations_code",
        "tutor_invitations",
        ["code"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_tutor_invitations_code",
        table_name="tutor_invitations",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("tutor_invitations", schema="xi_back_2")
    # ### end Alembic commands ###
