"""invoices_1

Revision ID: 030
Revises: 029
Create Date: 2025-06-29 17:48:15.102737

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "030"
down_revision: Union[str, None] = "029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_item_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_item_templates")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_invoice_item_templates_creator_user_id"),
        "invoice_item_templates",
        ["creator_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total", sa.Numeric(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_invoices_creator_user_id"),
        "invoices",
        ["creator_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "invoice_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["xi_back_2.invoices.id"],
            name=op.f("fk_invoice_items_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_items")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_invoice_items_invoice_id"),
        "invoice_items",
        ["invoice_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "recipient_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("recipient_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WF_PAYMENT",
                "WF_CONFIRMATION",
                "CANCELED",
                "COMPLETE",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["xi_back_2.invoices.id"],
            name=op.f("fk_recipient_invoices_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipient_invoices")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_recipient_invoices_invoice_id"),
        "recipient_invoices",
        ["invoice_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_recipient_invoices_recipient_user_id"),
        "recipient_invoices",
        ["recipient_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_recipient_invoices_recipient_user_id"),
        table_name="recipient_invoices",
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_recipient_invoices_invoice_id"),
        table_name="recipient_invoices",
        schema="xi_back_2",
    )
    op.drop_table("recipient_invoices", schema="xi_back_2")
    op.drop_index(
        op.f("ix_xi_back_2_invoice_items_invoice_id"),
        table_name="invoice_items",
        schema="xi_back_2",
    )
    op.drop_table("invoice_items", schema="xi_back_2")
    op.drop_index(
        op.f("ix_xi_back_2_invoices_creator_user_id"),
        table_name="invoices",
        schema="xi_back_2",
    )
    op.drop_table("invoices", schema="xi_back_2")
    op.drop_index(
        op.f("ix_xi_back_2_invoice_item_templates_creator_user_id"),
        table_name="invoice_item_templates",
        schema="xi_back_2",
    )
    op.drop_table("invoice_item_templates", schema="xi_back_2")
    # ### end Alembic commands ###
