"""tutor_materials_content

Revision ID: 033
Revises: 032
Create Date: 2025-07-11 15:13:28.297185

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "033"
down_revision: Union[str, None] = "032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # we don't have users yet, so it's fine to just delete data
    op.execute("TRUNCATE TABLE xi_back_2.tutor_materials")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tutor_materials",
        sa.Column("ydoc_id", sa.String(), nullable=False),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tutor_materials", "ydoc_id", schema="xi_back_2")
    # ### end Alembic commands ###
