"""user_contacts

Revision ID: 034
Revises: 033
Create Date: 2025-07-11 22:10:07.040025

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "034"
down_revision: Union[str, None] = "033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_contacts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind", sa.Enum("PERSONAL_TELEGRAM", name="contactkind"), nullable=False
        ),
        sa.Column("link", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "kind", name=op.f("pk_user_contacts")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_contacts", schema="xi_back_2")
    # ### end Alembic commands ###
    sa.Enum(name="contactkind").drop(bind=op.get_bind())
