"""telegram_connections

Revision ID: 035
Revises: 034
Create Date: 2025-07-14 21:55:51.604449

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "035"
down_revision: Union[str, None] = "034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_connections",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", "REPLACED", name="telegramconnectionstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_telegram_connections")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_telegram_connections_chat_id"),
        "telegram_connections",
        ["chat_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_telegram_connections_chat_id"),
        table_name="telegram_connections",
        schema="xi_back_2",
    )
    op.drop_table("telegram_connections", schema="xi_back_2")
    # ### end Alembic commands ###
    sa.Enum(name="telegramconnectionstatus").drop(op.get_bind())
