"""fix_invoices

Revision ID: 036
Revises: 035
Create Date: 2025-08-15 14:44:58.391414

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "036"
down_revision: Union[str, None] = "035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("TRUNCATE TABLE xi_back_2.invoices CASCADE")
    op.execute("TRUNCATE TABLE xi_back_2.invoice_item_templates")
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "invoice_item_templates",
        sa.Column("tutor_id", sa.Integer(), nullable=False),
        schema="xi_back_2",
    )
    op.drop_index(
        "ix_xi_back_2_invoice_item_templates_creator_user_id",
        table_name="invoice_item_templates",
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_invoice_item_templates_tutor_id"),
        "invoice_item_templates",
        ["tutor_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("invoice_item_templates", "creator_user_id", schema="xi_back_2")
    op.add_column(
        "invoices",
        sa.Column("tutor_id", sa.Integer(), nullable=False),
        schema="xi_back_2",
    )
    op.drop_index(
        "ix_xi_back_2_invoices_creator_user_id",
        table_name="invoices",
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_invoices_tutor_id"),
        "invoices",
        ["tutor_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("invoices", "creator_user_id", schema="xi_back_2")
    op.drop_column("invoices", "total", schema="xi_back_2")
    op.add_column(
        "recipient_invoices",
        sa.Column("student_id", sa.Integer(), nullable=False),
        schema="xi_back_2",
    )
    op.add_column(
        "recipient_invoices",
        sa.Column("total", sa.Numeric(), nullable=False),
        schema="xi_back_2",
    )
    op.drop_index(
        "ix_xi_back_2_recipient_invoices_recipient_user_id",
        table_name="recipient_invoices",
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_recipient_invoices_student_id"),
        "recipient_invoices",
        ["student_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("recipient_invoices", "recipient_user_id", schema="xi_back_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("TRUNCATE TABLE xi_back_2.invoices CASCADE")
    op.execute("TRUNCATE TABLE xi_back_2.invoice_item_templates")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipient_invoices",
        sa.Column(
            "recipient_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_recipient_invoices_student_id"),
        table_name="recipient_invoices",
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_recipient_invoices_recipient_user_id",
        "recipient_invoices",
        ["recipient_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("recipient_invoices", "total", schema="xi_back_2")
    op.drop_column("recipient_invoices", "student_id", schema="xi_back_2")
    op.add_column(
        "invoices",
        sa.Column("total", sa.NUMERIC(), autoincrement=False, nullable=False),
        schema="xi_back_2",
    )
    op.add_column(
        "invoices",
        sa.Column("creator_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_invoices_tutor_id"),
        table_name="invoices",
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_invoices_creator_user_id",
        "invoices",
        ["creator_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("invoices", "tutor_id", schema="xi_back_2")
    op.add_column(
        "invoice_item_templates",
        sa.Column("creator_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_invoice_item_templates_tutor_id"),
        table_name="invoice_item_templates",
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_invoice_item_templates_creator_user_id",
        "invoice_item_templates",
        ["creator_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_column("invoice_item_templates", "tutor_id", schema="xi_back_2")
    # ### end Alembic commands ###
