"""invoices_payment_type

Revision ID: 036
Revises: 035
Create Date: 2025-08-13 02:33:37.246188

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "036"
down_revision: Union[str, None] = "035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipient_invoices",
        sa.Column(
            "payment_type",
            sa.Enum("TRANSFER", "CASH", name="paymenttype"),
            nullable=True,
        ),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipient_invoices", "payment_type", schema="xi_back_2")
    # ### end Alembic commands ###
