"""tutorships

Revision ID: 038
Revises: 035
Create Date: 2025-08-22 22:02:25.728414

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "038"
down_revision: Union[str, None] = "035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutorships",
        sa.Column("tutor_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_classroom_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tutor_id", "student_id", name=op.f("pk_tutorships")),
        sa.CheckConstraint(
            "tutor_id != student_id", name="check_tutorship_tutor_id_ne_student_id"
        ),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tutorships", schema="xi_back_2")
    # ### end Alembic commands ###
