"""classroom-subjects

Revision ID: 039
Revises: 038
Create Date: 2025-09-07 10:29:52.193976

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "039"
down_revision: Union[str, None] = "038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classrooms",
        sa.Column("subject_id", sa.Integer(), nullable=True),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classrooms", "subject_id", schema="xi_back_2")
    # ### end Alembic commands ###
