"""invitation-index-fix

Revision ID: 039
Revises: 038
Create Date: 2025-08-22 22:26:46.873668

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "039"
down_revision: Union[str, None] = "038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_tutor_invitations_code",
        table_name="tutor_invitations",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_constraint(
        "uq_tutor_invitations_code",
        "tutor_invitations",
        schema="xi_back_2",
        type_="unique",
    )
    op.create_index(
        op.f("ix_xi_back_2_tutor_invitations_code"),
        "tutor_invitations",
        ["code"],
        unique=True,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_tutor_invitations_code"),
        table_name="tutor_invitations",
        schema="xi_back_2",
    )
    op.create_unique_constraint(
        "uq_tutor_invitations_code", "tutor_invitations", ["code"], schema="xi_back_2"
    )
    op.create_index(
        "hash_index_tutor_invitations_code",
        "tutor_invitations",
        ["code"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###
