"""required-display-name

Revision ID: 040
Revises: 039
Create Date: 2025-09-10 21:20:33.280985

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "040"
down_revision: Union[str, None] = "039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

schema_name = "xi_back_2"
table_name = "users"


def upgrade() -> None:
    bind = op.get_bind()

    metadata = sa.MetaData(schema=schema_name)
    User = sa.Table(table_name, metadata, autoload_with=bind)

    bind.execute(
        sa.update(User)
        .where(User.c.display_name.is_(None))
        .values(display_name=User.c.username)
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
