"""group_classrooms_enrollments_counter

Revision ID: 042
Revises: 041
Create Date: 2025-09-29 01:51:24.899004

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "042"
down_revision: Union[str, None] = "041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

schema_name = "xi_back_2"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classrooms",
        sa.Column("enrollments_count", sa.Integer(), nullable=True),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###

    bind = op.get_bind()

    metadata = sa.MetaData(schema=schema_name)

    Classroom = sa.Table("classrooms", metadata, autoload_with=bind)
    Enrollment = sa.Table("enrollments", metadata, autoload_with=bind)

    sub = (
        sa.select(
            Enrollment.c.group_classroom_id.label("group_classroom_id"),
            sa.func.count(Enrollment.c.student_id).label("count"),
        )
        .group_by(Enrollment.c.group_classroom_id)
        .subquery()
    )

    bind.execute(
        sa.update(Classroom)
        .values(enrollments_count=sub.c.count)
        .filter(Classroom.c.id == sub.c.group_classroom_id)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classrooms", "enrollments_count", schema="xi_back_2")
    # ### end Alembic commands ###
