"""classroom_invoices

Revision ID: 043
Revises: 042
Create Date: 2025-10-21 15:53:47.451234

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "043"
down_revision: Union[str, None] = "042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("TRUNCATE TABLE xi_back_2.invoices CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_invoices_classroom_id"),
        "invoices",
        ["classroom_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_invoices_classroom_id"),
        table_name="invoices",
        schema="xi_back_2",
    )
    op.drop_column("invoices", "classroom_id", schema="xi_back_2")
    # ### end Alembic commands ###
