"""platform_notifications

Revision ID: 044
Revises: 043
Create Date: 2025-10-24 01:06:13.981155

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "044"
down_revision: Union[str, None] = "043"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "recipient_notifications",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["xi_back_2.notifications.id"],
            name=op.f("fk_recipient_notifications_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_id",
            "recipient_user_id",
            name=op.f("pk_recipient_notifications"),
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_recipient_notifications_notification_id"),
        "recipient_notifications",
        ["notification_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_recipient_notifications_recipient_user_id"),
        "recipient_notifications",
        ["recipient_user_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_recipient_notifications_recipient_user_id"),
        table_name="recipient_notifications",
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_recipient_notifications_notification_id"),
        table_name="recipient_notifications",
        schema="xi_back_2",
    )
    op.drop_table("recipient_notifications", schema="xi_back_2")
    op.drop_index(
        op.f("ix_xi_back_2_notifications_created_at"),
        table_name="notifications",
        schema="xi_back_2",
    )
    op.drop_table("notifications", schema="xi_back_2")
    # ### end Alembic commands ###
