"""storage_v2

Revision ID: 046
Revises: 045
Create Date: 2025-10-25 20:04:45.059180

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "046"
down_revision: Union[str, None] = "045"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_groups")),
        schema="xi_back_2",
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind", sa.Enum("UNCATEGORIZED", "IMAGE", name="file_kind"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        schema="xi_back_2",
    )
    op.create_table(
        "ydocs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ydocs")),
        schema="xi_back_2",
    )
    op.create_table(
        "access_group_files",
        sa.Column("access_group_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups.id"],
            name=op.f("fk_access_group_files_access_group_id_access_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["xi_back_2.files.id"],
            name=op.f("fk_access_group_files_file_id_files"),
        ),
        sa.PrimaryKeyConstraint(
            "access_group_id", "file_id", name=op.f("pk_access_group_files")
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_access_group_files_access_group_id"),
        "access_group_files",
        ["access_group_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_access_group_files_file_id"),
        "access_group_files",
        ["file_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "access_group_ydocs",
        sa.Column("access_group_id", sa.Uuid(), nullable=False),
        sa.Column("ydoc_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups.id"],
            name=op.f("fk_access_group_ydocs_access_group_id_access_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ydoc_id"],
            ["xi_back_2.ydocs.id"],
            name=op.f("fk_access_group_ydocs_ydoc_id_ydocs"),
        ),
        sa.PrimaryKeyConstraint(
            "access_group_id", "ydoc_id", name=op.f("pk_access_group_ydocs")
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_access_group_ydocs_access_group_id"),
        "access_group_ydocs",
        ["access_group_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_access_group_ydocs_ydoc_id"),
        "access_group_ydocs",
        ["ydoc_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_access_group_ydocs_ydoc_id"),
        table_name="access_group_ydocs",
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_access_group_ydocs_access_group_id"),
        table_name="access_group_ydocs",
        schema="xi_back_2",
    )
    op.drop_table("access_group_ydocs", schema="xi_back_2")
    op.drop_index(
        op.f("ix_xi_back_2_access_group_files_file_id"),
        table_name="access_group_files",
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_access_group_files_access_group_id"),
        table_name="access_group_files",
        schema="xi_back_2",
    )
    op.drop_table("access_group_files", schema="xi_back_2")
    op.drop_table("ydocs", schema="xi_back_2")
    op.drop_table("files", schema="xi_back_2")
    op.drop_table("access_groups", schema="xi_back_2")
    # ### end Alembic commands ###
