"""classroom_notes

Revision ID: 047
Revises: 046
Create Date: 2025-10-25 21:56:04.810699

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "047"
down_revision: Union[str, None] = "046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classroom_notes",
        sa.Column("classroom_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("access_group_id", sa.String(), nullable=False),
        sa.Column("ydoc_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["xi_back_2.classrooms.id"],
            name=op.f("fk_classroom_notes_classroom_id_classrooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("classroom_id", name=op.f("pk_classroom_notes")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classroom_notes", schema="xi_back_2")
    # ### end Alembic commands ###
