"""materials_v2

Revision ID: 048
Revises: 047
Create Date: 2025-10-26 00:44:48.837213

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "048"
down_revision: Union[str, None] = "047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "access_kind",
            sa.Enum("TUTOR", "CLASSROOM", name="materialaccesskind"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("access_group_id", sa.String(), nullable=False),
        sa.Column(
            "content_kind",
            sa.Enum("NOTE", "BOARD", "FILE", name="materialcontentkind"),
            nullable=False,
        ),
        sa.Column("content_id", sa.String(), nullable=False),
        sa.Column("tutor_id", sa.Integer(), nullable=True),
        sa.Column("classroom_id", sa.Integer(), nullable=True),
        sa.Column(
            "student_access_mode",
            sa.Enum("NO_ACCESS", "READ_ONLY", "READ_WRITE", name="materialaccessmode"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("materials", schema="xi_back_2")
    # ### end Alembic commands ###
