"""remove_old_storage

Revision ID: 049
Revises: 048
Create Date: 2025-11-03 03:09:14.611474

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "049"
down_revision: Union[str, None] = "048"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ydocs_old", schema="xi_back_2")
    op.drop_table("files_old", schema="xi_back_2")
    op.drop_table("access_groups_old", schema="xi_back_2")
    op.drop_table("tutor_materials", schema="xi_back_2")
    # ### end Alembic commands ###
    bind = op.get_bind()
    sa.Enum(name="materialkind").drop(bind=bind)
    sa.Enum(name="filekind").drop(bind=bind)
    sa.Enum(name="storageaccessgroupkind").drop(bind=bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_materials",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_opened_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tutor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM("NOTE", "BOARD", name="materialkind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ydoc_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_tutor_materials"),
        schema="xi_back_2",
    )
    op.create_table(
        "files_old",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM("UNCATEGORIZED", "IMAGE", name="filekind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("creator_user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("access_group_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups_old.id"],
            name="fk_files_old_access_group_id_access_groups_old",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_files_old"),
        schema="xi_back_2",
    )
    op.create_table(
        "ydocs_old",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("access_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups_old.id"],
            name="fk_ydocs_old_access_group_id_access_groups_old",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ydocs_old"),
        schema="xi_back_2",
    )
    op.create_table(
        "access_groups_old",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM("BOARD_CHANNEL", "PERSONAL", name="storageaccessgroupkind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("related_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_access_groups_old"),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
