"""user_email_refactoring

Revision ID: 050
Revises: 049
Create Date: 2025-11-04 21:42:11.098620

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "050"
down_revision: Union[str, None] = "049"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_session_token",
        table_name="sessions",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("sessions", schema="xi_back_2")
    op.drop_index(
        "hash_index_users_email",
        table_name="users",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_index(
        "hash_index_users_token",
        table_name="users",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_index(
        "hash_index_users_username",
        table_name="users",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("users", schema="xi_back_2")

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=30), nullable=False),
        sa.Column("default_layout", sa.String(length=10), nullable=True),
        sa.Column("theme", sa.String(length=10), nullable=False),
        sa.Column(
            "onboarding_stage",
            sa.Enum(
                "EMAIL_CONFIRMATION",
                "USER_INFORMATION",
                "DEFAULT_LAYOUT",
                "NOTIFICATIONS",
                "TRAINING",
                "COMPLETED",
                name="onboarding_stage_3",
            ),
            nullable=False,
        ),
        sa.Column(
            "email_confirmation_resend_allowed_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "password_last_changed_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_users_email",
        "users",
        ["email"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_index(
        "hash_index_users_username",
        "users",
        ["username"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.CHAR(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_cross_site", sa.Boolean(), nullable=False),
        sa.Column("is_mub", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["xi_back_2.users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_session_token",
        "sessions",
        ["token"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###

    sa.Enum(name="onboarding_stage_2").drop(bind=op.get_bind())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_session_token",
        table_name="sessions",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("sessions", schema="xi_back_2")
    op.drop_index(
        "hash_index_users_username",
        table_name="users",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_index(
        "hash_index_users_email",
        table_name="users",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("users", schema="xi_back_2")

    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('xi_back_2.users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "password", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_name", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column("theme", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column(
            "reset_token", sa.CHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_password_change",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email_confirmed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "allowed_confirmation_resend",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "default_layout", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "onboarding_stage",
            postgresql.ENUM(
                "USER_INFORMATION",
                "DEFAULT_LAYOUT",
                "NOTIFICATIONS",
                "TRAINING",
                "COMPLETED",
                name="onboarding_stage_2",
            ),
            server_default=sa.text("'USER_INFORMATION'::onboarding_stage_2"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        schema="xi_back_2",
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "hash_index_users_username",
        "users",
        ["username"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_index(
        "hash_index_users_token",
        "users",
        ["reset_token"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_index(
        "hash_index_users_email",
        "users",
        ["email"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("token", sa.CHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_disabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_cross_site", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_mub", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["xi_back_2.users.id"],
            name="fk_sessions_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sessions"),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_session_token",
        "sessions",
        ["token"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###

    sa.Enum(name="onboarding_stage_3").drop(bind=op.get_bind())
