"""only_one_ydoc

Revision ID: 051
Revises: 050
Create Date: 2025-11-08 21:34:30.324571

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "051"
down_revision: Union[str, None] = "050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "access_groups",
        sa.Column("main_ydoc_id", sa.Uuid(), nullable=True),
        schema="xi_back_2",
    )

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    AccessGroupYDoc = sa.Table("access_group_ydocs", metadata, autoload_with=connection)
    AccessGroup = sa.Table("access_groups", metadata, autoload_with=connection)

    connection.execute(
        sa.update(AccessGroup).values(
            main_ydoc_id=(
                sa.select(AccessGroupYDoc.c.ydoc_id)
                .where(AccessGroupYDoc.c.access_group_id == AccessGroup.c.id)
                .limit(1)
                .scalar_subquery()
            )
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_xi_back_2_access_group_ydocs_access_group_id",
        table_name="access_group_ydocs",
        schema="xi_back_2",
    )
    op.drop_index(
        "ix_xi_back_2_access_group_ydocs_ydoc_id",
        table_name="access_group_ydocs",
        schema="xi_back_2",
    )
    op.drop_table("access_group_ydocs", schema="xi_back_2")
    op.alter_column(
        "access_groups",
        column_name="main_ydoc_id",
        nullable=False,
        schema="xi_back_2",
    )
    op.create_foreign_key(
        op.f("fk_access_groups_main_ydoc_id_ydocs"),
        "access_groups",
        "ydocs",
        ["main_ydoc_id"],
        ["id"],
        source_schema="xi_back_2",
        referent_schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_group_ydocs",
        sa.Column("access_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("ydoc_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups.id"],
            name="fk_access_group_ydocs_access_group_id_access_groups",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ydoc_id"],
            ["xi_back_2.ydocs.id"],
            name="fk_access_group_ydocs_ydoc_id_ydocs",
        ),
        sa.PrimaryKeyConstraint(
            "access_group_id", "ydoc_id", name="pk_access_group_ydocs"
        ),
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_access_group_ydocs_ydoc_id",
        "access_group_ydocs",
        ["ydoc_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_access_group_ydocs_access_group_id",
        "access_group_ydocs",
        ["access_group_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    AccessGroupYDoc = sa.Table("access_group_ydocs", metadata, autoload_with=connection)
    AccessGroup = sa.Table("access_groups", metadata, autoload_with=connection)

    connection.execute(
        sa.insert(AccessGroupYDoc).from_select(
            ["access_group_id", "ydoc_id"],
            sa.select(AccessGroup.c.id, AccessGroup.c.main_ydoc_id),
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_access_groups_main_ydoc_id_ydocs"),
        "access_groups",
        schema="xi_back_2",
        type_="foreignkey",
    )
    op.drop_column("access_groups", "main_ydoc_id", schema="xi_back_2")
    # ### end Alembic commands ###
