"""email_connections

Revision ID: 052
Revises: 051
Create Date: 2025-11-11 20:51:09.142765

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "052"
down_revision: Union[str, None] = "051"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_connections",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_email_connections")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_email_connections_email"),
        "email_connections",
        ["email"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    User = sa.Table("users", metadata, autoload_with=connection)
    EmailConnection = sa.Table("email_connections", metadata, autoload_with=connection)

    connection.execute(
        sa.insert(EmailConnection).from_select(
            ["user_id", "email"],
            sa.select(User.c.id, User.c.email),
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_email_connections_email"),
        table_name="email_connections",
        schema="xi_back_2",
    )
    op.drop_table("email_connections", schema="xi_back_2")
    # ### end Alembic commands ###
