"""basic_datalake_events

Revision ID: 053
Revises: 052
Create Date: 2025-11-14 22:55:32.135968

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "053"
down_revision: Union[str, None] = "052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datalake_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datalake_events")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_datalake_events_recorded_at"),
        "datalake_events",
        ["recorded_at"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_datalake_events_recorded_at"),
        table_name="datalake_events",
        schema="xi_back_2",
    )
    op.drop_table("datalake_events", schema="xi_back_2")
    # ### end Alembic commands ###
