"""users_created_at

Revision ID: 054
Revises: 053
Create Date: 2025-11-15 09:15:32.247534

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "054"
down_revision: Union[str, None] = "053"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        schema="xi_back_2",
    )

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    User = sa.Table("users", metadata, autoload_with=connection)

    connection.execute(
        sa.update(User).values(created_at=User.c.password_last_changed_at)
        # Good approximation for most users in production, although not perfect
    )

    op.alter_column(
        "users",
        column_name="created_at",
        nullable=False,
        schema="xi_back_2",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at", schema="xi_back_2")
    # ### end Alembic commands ###
