"""classroom_events

Revision ID: 055
Revises: 054
Create Date: 2025-11-21 00:41:26.686639

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "055"
down_revision: Union[str, None] = "054"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EventKind = sa.Enum("CLASSROOM", name="eventkind")


def upgrade() -> None:
    op.execute("TRUNCATE TABLE xi_back_2.scheduler_events")
    EventKind.create(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scheduler_events",
        sa.Column("kind", EventKind, nullable=False),
        schema="xi_back_2",
    )
    op.add_column(
        "scheduler_events",
        sa.Column("classroom_id", sa.Integer(), nullable=True),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduler_events", "classroom_id", schema="xi_back_2")
    op.drop_column("scheduler_events", "kind", schema="xi_back_2")
    # ### end Alembic commands ###
    EventKind.drop(bind=op.get_bind())
