"""classroom_events_2_0

Revision ID: 057
Revises: 056
Create Date: 2026-04-28 01:01:43.574455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import BIT

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "057"
down_revision: Union[str, None] = "056"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scheduler_events", schema="xi_back_2")
    sa.Enum(name="eventkind").drop(bind=op.get_bind())
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("kind", sa.Enum("CLASSROOM", name="eventkind"), nullable=False),
        sa.Column("classroom_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        schema="xi_back_2",
    )
    op.create_table(
        "repetition_modes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind", sa.Enum("DAILY", "WEEKLY", name="repetitionkind"), nullable=False
        ),
        sa.Column(
            "starts_at",
            postgresql.TIMESTAMP(timezone=True, precision=0),
            nullable=False,
        ),
        sa.Column(
            "ends_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False
        ),
        sa.Column("is_finite", sa.Boolean(), nullable=True),
        sa.Column(
            "weekly_starting_bitmask",
            BIT(length=7),
            nullable=True,
        ),
        sa.Column(
            "weekly_combined_bitmask",
            BIT(length=7),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["xi_back_2.events.id"],
            name=op.f("fk_repetition_modes_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repetition_modes")),
        schema="xi_back_2",
    )
    op.create_index(
        "index_repetition_modes_kind_and_interval",
        "repetition_modes",
        ["kind", "starts_at", "ends_at"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_repetition_modes_event_id"),
        "repetition_modes",
        ["event_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "event_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("SOLE", "REPEATED", name="eventinstancekind"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "starts_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True
        ),
        sa.Column(
            "ends_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True
        ),
        sa.Column("repetition_mode_id", sa.Uuid(), nullable=True),
        sa.Column("instance_index", sa.Integer(), nullable=True),
        sa.Column(
            "starts_at_override",
            postgresql.TIMESTAMP(timezone=True, precision=0),
            nullable=True,
        ),
        sa.Column(
            "ends_at_override",
            postgresql.TIMESTAMP(timezone=True, precision=0),
            nullable=True,
        ),
        sa.Column("name_override", sa.String(length=100), nullable=True),
        sa.Column("description_override", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["xi_back_2.events.id"],
            name=op.f("fk_event_instances_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repetition_mode_id"],
            ["xi_back_2.repetition_modes.id"],
            name=op.f("fk_event_instances_repetition_mode_id_repetition_modes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_instances")),
        schema="xi_back_2",
    )
    op.create_index(
        "index_repeated_event_instance_interval_override",
        "event_instances",
        ["starts_at_override", "ends_at_override"],
        unique=False,
        schema="xi_back_2",
        postgresql_where=sa.text(
            "kind = 'REPEATED' AND starts_at_override IS NOT NULL AND ends_at_override IS NOT NULL"
        ),
    )
    op.create_index(
        "index_repeated_event_instances_ids",
        "event_instances",
        ["repetition_mode_id", "instance_index"],
        unique=False,
        schema="xi_back_2",
        postgresql_where=sa.text("kind = 'REPEATED'"),
    )
    op.create_index(
        "index_sole_event_instance_interval",
        "event_instances",
        ["starts_at", "ends_at"],
        unique=False,
        schema="xi_back_2",
        postgresql_where=sa.text("kind = 'SOLE'"),
    )
    op.create_index(
        "unique_index_sole_event_instances_event_id",
        "event_instances",
        ["event_id"],
        unique=True,
        schema="xi_back_2",
        postgresql_where=sa.text("kind = 'SOLE'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_index_sole_event_instances_event_id",
        table_name="event_instances",
        schema="xi_back_2",
        postgresql_where=sa.text("kind = 'SOLE'"),
    )
    op.drop_index(
        "index_sole_event_instance_interval",
        table_name="event_instances",
        schema="xi_back_2",
        postgresql_where=sa.text("kind = 'SOLE'"),
    )
    op.drop_index(
        "index_repeated_event_instances_ids",
        table_name="event_instances",
        schema="xi_back_2",
        postgresql_where=sa.text("kind = 'REPEATED'"),
    )
    op.drop_index(
        "index_repeated_event_instance_interval_override",
        table_name="event_instances",
        schema="xi_back_2",
        postgresql_where=sa.text(
            "kind = 'REPEATED' AND starts_at_override IS NOT NULL AND ends_at_override IS NOT NULL"
        ),
    )
    op.drop_table("event_instances", schema="xi_back_2")
    op.drop_index(
        op.f("ix_xi_back_2_repetition_modes_event_id"),
        table_name="repetition_modes",
        schema="xi_back_2",
    )
    op.drop_index(
        "index_repetition_modes_kind_and_interval",
        table_name="repetition_modes",
        schema="xi_back_2",
    )
    op.drop_table("repetition_modes", schema="xi_back_2")
    op.drop_table("events", schema="xi_back_2")
    sa.Enum(name="eventkind").drop(bind=op.get_bind())
    op.create_table(
        "scheduler_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "starts_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ends_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=1000), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kind",
            postgresql.ENUM("CLASSROOM", name="eventkind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("classroom_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_scheduler_events"),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
