"""notification-idempotency

Revision ID: 058
Revises: 057
Create Date: 2026-06-15 00:57:00.751009

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "058"
down_revision: Union[str, None] = "057"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        schema="xi_back_2",
    )
    op.add_column(
        "notifications",
        sa.Column("idempotency_expires_at", sa.DateTime(timezone=True), nullable=True),
        schema="xi_back_2",
    )
    op.create_index(
        "unique_index_notifications_idempotency",
        "notifications",
        ["idempotency_key"],
        unique=True,
        schema="xi_back_2",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_index_notifications_idempotency",
        table_name="notifications",
        schema="xi_back_2",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_column("notifications", "idempotency_expires_at", schema="xi_back_2")
    op.drop_column("notifications", "idempotency_key", schema="xi_back_2")
    # ### end Alembic commands ###
