"""event_reminders

Revision ID: 059
Revises: 058
Create Date: 2026-07-11 01:02:40.765898

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "059"
down_revision: Union[str, None] = "058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "index_repetition_modes_starts_at_utc_time",
        "repetition_modes",
        [
            sa.literal_column(
                "CAST(timezone('UTC', starts_at) AS TIME WITHOUT TIME ZONE)"
            )
        ],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_repetition_modes_starts_at_utc_time",
        table_name="repetition_modes",
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
