"""delivery_methods

Revision ID: 060
Revises: 059
Create Date: 2026-07-11 01:02:40.765898

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "060"
down_revision: Union[str, None] = "059"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_methods",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("EMAIL", "TELEGRAM", name="deliverymethodkind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", "REPLACED", name="deliverymethodstatus"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("peer_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "kind", name=op.f("pk_delivery_methods")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_delivery_methods_email"),
        "delivery_methods",
        ["email"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_delivery_methods_peer_id"),
        "delivery_methods",
        ["peer_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        "unique_index_delivery_methods_active_or_blocked_peer_id",
        "delivery_methods",
        ["kind", "peer_id"],
        unique=True,
        schema="xi_back_2",
        postgresql_where=sa.text(
            "kind = 'TELEGRAM' AND status IN ('ACTIVE', 'BLOCKED')"
        ),
    )
    # ### end Alembic commands ###

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    DeliveryMethod = sa.Table("delivery_methods", metadata, autoload_with=connection)
    EmailConnection = sa.Table("email_connections", metadata, autoload_with=connection)
    TelegramConnection = sa.Table(
        "telegram_connections", metadata, autoload_with=connection
    )

    connection.execute(
        sa.insert(DeliveryMethod).from_select(
            [
                DeliveryMethod.c.user_id,
                DeliveryMethod.c.kind,
                DeliveryMethod.c.status,
                DeliveryMethod.c.email,
            ],
            sa.select(
                EmailConnection.c.user_id,
                sa.literal_column("'EMAIL'::deliverymethodkind"),
                sa.literal_column("'ACTIVE'::deliverymethodstatus"),
                EmailConnection.c.email,
            ),
        )
    )

    connection.execute(
        sa.insert(DeliveryMethod).from_select(
            [
                DeliveryMethod.c.user_id,
                DeliveryMethod.c.kind,
                DeliveryMethod.c.status,
                DeliveryMethod.c.peer_id,
            ],
            sa.select(
                TelegramConnection.c.user_id,
                sa.literal_column("'TELEGRAM'::deliverymethodkind"),
                sa.literal_column("CAST(status AS TEXT)::deliverymethodstatus"),
                TelegramConnection.c.chat_id,
            ),
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_xi_back_2_email_connections_email",
        table_name="email_connections",
        schema="xi_back_2",
    )
    op.drop_table("email_connections", schema="xi_back_2")
    op.drop_index(
        "ix_xi_back_2_telegram_connections_chat_id",
        table_name="telegram_connections",
        schema="xi_back_2",
    )
    op.drop_table("telegram_connections", schema="xi_back_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_connections",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "BLOCKED", "REPLACED", name="telegramconnectionstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name="pk_telegram_connections"),
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_telegram_connections_chat_id",
        "telegram_connections",
        ["chat_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_table(
        "email_connections",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="pk_email_connections"),
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_email_connections_email",
        "email_connections",
        ["email"],
        unique=False,
        schema="xi_back_2",
    )
    op.drop_index(
        "unique_index_delivery_methods_active_or_blocked_peer_id",
        table_name="delivery_methods",
        schema="xi_back_2",
        postgresql_where=sa.text(
            "kind = 'TELEGRAM' AND status IN ('ACTIVE', 'BLOCKED')"
        ),
    )
    op.drop_index(
        op.f("ix_xi_back_2_delivery_methods_peer_id"),
        table_name="delivery_methods",
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_delivery_methods_email"),
        table_name="delivery_methods",
        schema="xi_back_2",
    )
    op.drop_table("delivery_methods", schema="xi_back_2")
    # ### end Alembic commands ###

    sa.Enum(name="deliverymethodkind").drop(bind=op.get_bind())
    sa.Enum(name="deliverymethodstatus").drop(bind=op.get_bind())
