"""disabled_delivery_routes

Revision ID: 061
Revises: 060
Create Date: 2026-07-11 02:07:17.116122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "061"
down_revision: Union[str, None] = "060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disabled_delivery_routes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "delivery_method_kind",
            postgresql.ENUM(
                "EMAIL", "TELEGRAM", name="deliverymethodkind", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "notification_category",
            sa.Enum(
                "CLASSROOMS",
                "INVOICES",
                "EVENTS",
                "EVENT_REMINDERS",
                name="notificationcategory",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "delivery_method_kind",
            "notification_category",
            name=op.f("pk_disabled_delivery_routes"),
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_disabled_delivery_routes_user_id"),
        "disabled_delivery_routes",
        ["user_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_disabled_delivery_routes_user_id"),
        table_name="disabled_delivery_routes",
        schema="xi_back_2",
    )
    op.drop_table("disabled_delivery_routes", schema="xi_back_2")
    # ### end Alembic commands ###

    sa.Enum(name="notificationcategory").drop(bind=op.get_bind())
