"""individual classroom name override

Revision ID: 064
Revises: 063
Create Date: 2026-08-11 19:20:14.459275

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "064"
down_revision: Union[str, None] = "063"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classrooms",
        sa.Column("student_name_override", sa.String(length=100), nullable=True),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classrooms", "student_name_override", schema="xi_back_2")
    # ### end Alembic commands ###
