"""remove-communities-service

Revision ID: 065
Revises: 064
Create Date: 2026-08-16 22:58:42.276915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "065"
down_revision: Union[str, None] = "064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("board_channels", schema="xi_back_2")
    op.drop_table("call_channels", schema="xi_back_2")
    op.drop_table("chat_channels", schema="xi_back_2")

    op.drop_index(
        "hash_index_tasks_channel_id",
        table_name="tasks",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("tasks", schema="xi_back_2")
    op.drop_table("task_channels", schema="xi_back_2")

    op.drop_index(
        "hash_index_channels_category_id",
        table_name="channels",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_index(
        "hash_index_channels_community_id",
        table_name="channels",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("channels", schema="xi_back_2")

    op.drop_index(
        "hash_index_categories_community_id",
        table_name="categories",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("categories", schema="xi_back_2")

    op.drop_index(
        "hash_index_invitations_token",
        table_name="invitations",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_index(
        "hash_index_invitations_community_id",
        table_name="invitations",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("invitations", schema="xi_back_2")

    op.drop_index(
        "hash_index_community_id",
        table_name="participants",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_index(
        "hash_index_user_id",
        table_name="participants",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("participants", schema="xi_back_2")

    op.drop_table("communities", schema="xi_back_2")
    # ### end Alembic commands ###

    bind = op.get_bind()
    sa.Enum(name="channeltype").drop(bind=bind)
    sa.Enum(name="_channeltype").drop(bind=bind)
    sa.Enum(name="taskkind").drop(bind=bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communities",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('xi_back_2.communities_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_community"),
        schema="xi_back_2",
        postgresql_ignore_search_path=False,
    )

    op.create_table(
        "participants",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("is_owner", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["xi_back_2.communities.id"],
            name="fk_participants_community_id_communities",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_participants"),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_user_id",
        "participants",
        ["user_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_index(
        "hash_index_community_id",
        "participants",
        ["community_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )

    op.create_table(
        "invitations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.CHAR(length=10), autoincrement=False, nullable=False),
        sa.Column(
            "expiry",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("usage_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("usage_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "creator_id",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["xi_back_2.communities.id"],
            name="fk_invitations_community_id_communities",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_invitations"),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_invitations_token",
        "invitations",
        ["token"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_index(
        "hash_index_invitations_community_id",
        "invitations",
        ["community_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )

    op.create_table(
        "categories",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["xi_back_2.communities.id"],
            name="fk_categories_community_id_communities",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_categories"),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_categories_community_id",
        "categories",
        ["community_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )

    op.create_table(
        "channels",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "POSTS", "TASKS", "BOARD", "CHAT", "CALL", name="channeltype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('xi_back_2.channels_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["xi_back_2.categories.id"],
            name="fk_channels_category_id_categories",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["xi_back_2.communities.id"],
            name="fk_channels_community_id_communities",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_channels"),
        schema="xi_back_2",
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "hash_index_channels_community_id",
        "channels",
        ["community_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.create_index(
        "hash_index_channels_category_id",
        "channels",
        ["category_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )

    op.create_table(
        "task_channels",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["xi_back_2.channels.id"],
            name="fk_task_channels_id_channels",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_task_channels"),
        schema="xi_back_2",
        postgresql_ignore_search_path=False,
    )

    op.create_table(
        "tasks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM("TASK", "TEST", name="taskkind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "opening_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "closing_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["xi_back_2.task_channels.id"],
            name="fk_tasks_channel_id_task_channels",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_tasks"),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_tasks_channel_id",
        "tasks",
        ["channel_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )

    op.create_table(
        "chat_channels",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["xi_back_2.channels.id"],
            name="fk_chat_channels_id_channels",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chat_channels"),
        schema="xi_back_2",
    )
    op.create_table(
        "call_channels",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["xi_back_2.channels.id"],
            name="fk_call_channels_id_channels",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_call_channels"),
        schema="xi_back_2",
    )
    op.create_table(
        "board_channels",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("access_group_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ydoc_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["xi_back_2.channels.id"],
            name="fk_board_channels_id_channels",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_board_channels"),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
