"""remove-posts-service

Revision ID: 066
Revises: 065
Create Date: 2026-08-16 23:14:32.665580

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "066"
down_revision: Union[str, None] = "065"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_posts_channel_id",
        table_name="posts",
        schema="xi_back_2",
        postgresql_using="hash",
    )
    op.drop_table("posts", schema="xi_back_2")

    op.drop_table("post_channels", schema="xi_back_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_channels",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_post_channels"),
        schema="xi_back_2",
    )

    op.create_table(
        "posts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["xi_back_2.post_channels.id"],
            name="fk_posts_channel_id_post_channels",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_posts"),
        schema="xi_back_2",
    )
    op.create_index(
        "hash_index_posts_channel_id",
        "posts",
        ["channel_id"],
        unique=False,
        schema="xi_back_2",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###
