"""remove-messenger-service

Revision ID: 067
Revises: 066
Create Date: 2026-08-16 23:16:35.881131

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "067"
down_revision: Union[str, None] = "066"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("created_at_sort_index", table_name="messages", schema="xi_back_2")
    op.drop_index(
        "ix_xi_back_2_messages_chat_id", table_name="messages", schema="xi_back_2"
    )
    op.drop_index(
        "pinned_messages_created_at_sort_index",
        table_name="messages",
        schema="xi_back_2",
        postgresql_where="(pinned IS TRUE)",
    )
    op.drop_table("messages", schema="xi_back_2")

    op.drop_table("message_drafts", schema="xi_back_2")

    op.drop_table("chat_users", schema="xi_back_2")

    op.drop_table("chats", schema="xi_back_2")
    # ### end Alembic commands ###

    bind = op.get_bind()
    sa.Enum(name="chataccesskind").drop(bind=bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('xi_back_2.chats_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "access_kind",
            postgresql.ENUM("CHAT_CHANNEL", name="chataccesskind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("related_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_chats"),
        schema="xi_back_2",
        postgresql_ignore_search_path=False,
    )

    op.create_table(
        "chat_users",
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_message_read",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["xi_back_2.chats.id"],
            name="fk_chat_users_chat_id_chats",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chat_id", "user_id", name="pk_chat_users"),
        schema="xi_back_2",
    )

    op.create_table(
        "message_drafts",
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["xi_back_2.chats.id"],
            name="fk_message_drafts_chat_id_chats",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chat_id", "user_id", name="pk_message_drafts"),
        schema="xi_back_2",
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("sender_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "pinned",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["xi_back_2.chats.id"],
            name="fk_messages_chat_id_chats",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_messages"),
        schema="xi_back_2",
    )
    op.create_index(
        "pinned_messages_created_at_sort_index",
        "messages",
        [sa.literal_column("created_at DESC")],
        unique=False,
        schema="xi_back_2",
        postgresql_where="(pinned IS TRUE)",
    )
    op.create_index(
        "ix_xi_back_2_messages_chat_id",
        "messages",
        ["chat_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        "created_at_sort_index",
        "messages",
        [sa.literal_column("created_at DESC")],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
