"""content_ydocs_and_files

Revision ID: 071
Revises: 070
Create Date: 2026-08-19 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "071"
down_revision: Union[str, None] = "070"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ydocs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "content_kind",
            sa.Enum("NOTE", "BOARD", name="content_ydoc_kind"),
            nullable=False,
        ),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ydocs")),
        schema="xi_back_2",
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("uploader_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "UNCATEGORIZED",
                "IMAGE",
                "DOCUMENT",
                "AUDIO",
                name="content_file_kind",
            ),
            nullable=False,
        ),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        schema="xi_back_2",
    )
    op.create_table(
        "ydoc_files",
        sa.Column("ydoc_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ydoc_id"],
            ["xi_back_2.ydocs.id"],
            name=op.f("fk_ydoc_files_ydoc_id_ydocs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["xi_back_2.files.id"],
            name=op.f("fk_ydoc_files_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ydoc_id", "file_id", name=op.f("pk_ydoc_files")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_ydoc_files_file_id"),
        "ydoc_files",
        ["file_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_ydoc_files_file_id"),
        table_name="ydoc_files",
        schema="xi_back_2",
    )
    op.drop_table("ydoc_files", schema="xi_back_2")
    op.drop_table("files", schema="xi_back_2")
    op.drop_table("ydocs", schema="xi_back_2")
    # ### end Alembic commands ###

    bind = op.get_bind()
    sa.Enum(name="content_file_kind").drop(bind=bind)
    sa.Enum(name="content_ydoc_kind").drop(bind=bind)
