"""materials

Revision ID: 074
Revises: 073
Create Date: 2026-08-21 05:51:47.979958

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074"
down_revision: Union[str, None] = "073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "access_kind",
            sa.Enum("PERSONAL", "CLASSROOM", name="content_material_access_kind"),
            nullable=False,
        ),
        sa.Column("main_ydoc_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tutor_id", sa.Integer(), nullable=True),
        sa.Column("classroom_id", sa.Integer(), nullable=True),
        sa.Column(
            "student_access_mode",
            sa.Enum(
                "NO_ACCESS",
                "READ_ONLY",
                "READ_WRITE",
                name="content_material_access_mode",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["main_ydoc_id"],
            ["xi_back_2.ydocs.id"],
            name=op.f("fk_materials_main_ydoc_id_ydocs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("main_ydoc_id", name=op.f("uq_materials_main_ydoc_id")),
        schema="xi_back_2",
    )
    op.create_index(
        "index_materials_classroom_id_updated_at",
        "materials",
        ["classroom_id", "updated_at"],
        unique=False,
        schema="xi_back_2",
        postgresql_where=sa.text("access_kind = 'CLASSROOM'"),
    )
    op.create_index(
        "index_materials_student_accessible_classroom_id_updated_at",
        "materials",
        ["classroom_id", "updated_at"],
        unique=False,
        schema="xi_back_2",
        postgresql_where=sa.text(
            "access_kind = 'CLASSROOM' AND student_access_mode IN ('READ_ONLY', 'READ_WRITE')"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_materials_student_accessible_classroom_id_updated_at",
        table_name="materials",
        schema="xi_back_2",
        postgresql_where=sa.text(
            "access_kind = 'CLASSROOM' AND student_access_mode IN ('READ_ONLY', 'READ_WRITE')"
        ),
    )
    op.drop_index(
        "index_materials_classroom_id_updated_at",
        table_name="materials",
        schema="xi_back_2",
        postgresql_where=sa.text("access_kind = 'CLASSROOM'"),
    )
    op.drop_table("materials", schema="xi_back_2")
    # ### end Alembic commands ###

    bind = op.get_bind()
    sa.Enum(name="content_material_access_mode").drop(bind=bind)
    sa.Enum(name="content_material_access_kind").drop(bind=bind)
