"""index_ydocs_owner_id

Revision ID: 076
Revises: 075
Create Date: 2026-08-23 09:18:52.750301

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "076"
down_revision: Union[str, None] = "075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_xi_back_2_ydocs_owner_id"),
        "ydocs",
        ["owner_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_ydocs_owner_id"), table_name="ydocs", schema="xi_back_2"
    )
    # ### end Alembic commands ###
