"""remove_legacy_content

Revision ID: 078
Revises: 077
Create Date: 2026-08-25 04:37:19.717000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "078"
down_revision: Union[str, None] = "077"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_xi_back_2_access_group_files_access_group_id",
        table_name="access_group_files",
        schema="xi_back_2",
    )
    op.drop_index(
        "ix_xi_back_2_access_group_files_file_id",
        table_name="access_group_files",
        schema="xi_back_2",
    )
    op.drop_table("access_group_files", schema="xi_back_2")
    op.drop_table("classroom_notes", schema="xi_back_2")
    op.drop_table("materials_old", schema="xi_back_2")
    op.drop_table("access_groups", schema="xi_back_2")
    op.drop_table("files_old", schema="xi_back_2")
    op.drop_table("ydocs_old", schema="xi_back_2")
    # ### end Alembic commands ###
    bind = op.get_bind()
    sa.Enum(name="file_kind").drop(bind=bind)
    sa.Enum(name="materialaccesskind").drop(bind=bind)
    sa.Enum(name="materialcontentkind").drop(bind=bind)
    sa.Enum(name="materialaccessmode").drop(bind=bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ydocs_old",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_ydocs_old"),
        schema="xi_back_2",
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "files_old",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "UNCATEGORIZED", "IMAGE", "DOCUMENT", "AUDIO", name="file_kind"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_files_old"),
        schema="xi_back_2",
    )
    op.create_table(
        "access_groups",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("main_ydoc_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["main_ydoc_id"],
            ["xi_back_2.ydocs_old.id"],
            name="fk_access_groups_main_ydoc_id_ydocs_old",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_access_groups"),
        schema="xi_back_2",
    )
    op.create_table(
        "materials_old",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "access_kind",
            postgresql.ENUM("TUTOR", "CLASSROOM", name="materialaccesskind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("access_group_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "content_kind",
            postgresql.ENUM("NOTE", "BOARD", "FILE", name="materialcontentkind"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("tutor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("classroom_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "student_access_mode",
            postgresql.ENUM(
                "NO_ACCESS", "READ_ONLY", "READ_WRITE", name="materialaccessmode"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_materials_old"),
        schema="xi_back_2",
    )
    op.create_table(
        "classroom_notes",
        sa.Column("classroom_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("access_group_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ydoc_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["xi_back_2.classrooms.id"],
            name="fk_classroom_notes_classroom_id_classrooms",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("classroom_id", name="pk_classroom_notes"),
        schema="xi_back_2",
    )
    op.create_table(
        "access_group_files",
        sa.Column("access_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("file_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["xi_back_2.access_groups.id"],
            name="fk_access_group_files_access_group_id_access_groups",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["xi_back_2.files_old.id"],
            name="fk_access_group_files_file_id_files_old",
        ),
        sa.PrimaryKeyConstraint(
            "access_group_id", "file_id", name="pk_access_group_files"
        ),
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_access_group_files_file_id",
        "access_group_files",
        ["file_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        "ix_xi_back_2_access_group_files_access_group_id",
        "access_group_files",
        ["access_group_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
