"""file_library

Revision ID: 079
Revises: 078
Create Date: 2026-08-23 10:19:23.087414

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "079"
down_revision: Union[str, None] = "078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "index_files_owner_id_created_at",
        "files",
        ["owner_id", "created_at"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_files_owner_id_created_at", table_name="files", schema="xi_back_2"
    )
    # ### end Alembic commands ###
