"""tags

Revision ID: 080
Revises: 079
Create Date: 2026-08-25 06:27:37.489526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "080"
down_revision: Union[str, None] = "079"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Enum("SUBJECT", name="tagkind"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tutor_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        schema="xi_back_2",
    )
    op.create_index(
        "unique_index_tags_kind_tutor_id_name",
        "tags",
        ["kind", "tutor_id", "name"],
        unique=True,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    Tag = sa.Table("tags", metadata, autoload_with=connection)
    Subject = sa.Table("subjects", metadata, autoload_with=connection)

    connection.execute(
        sa.insert(Tag).from_select(
            [Tag.c.id, Tag.c.kind, Tag.c.name, Tag.c.tutor_id],
            sa.select(
                Subject.c.id,
                sa.literal_column("'SUBJECT'::tagkind"),
                Subject.c.name,
                Subject.c.tutor_id,
            ),
        )
    )
    connection.execute(
        sa.text(
            "SELECT setval("
            "pg_get_serial_sequence('xi_back_2.tags', 'id'), "
            "COALESCE((SELECT MAX(id) FROM xi_back_2.tags), 1), "
            "(SELECT MAX(id) FROM xi_back_2.tags) IS NOT NULL"
            ")"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_index_subjects_tutor_id_name", table_name="subjects", schema="xi_back_2"
    )
    op.drop_table("subjects", schema="xi_back_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("tutor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_subjects"),
        schema="xi_back_2",
    )
    op.create_index(
        "unique_index_subjects_tutor_id_name",
        "subjects",
        ["tutor_id", "name"],
        unique=True,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###

    connection = op.get_bind()
    metadata = sa.MetaData(schema="xi_back_2")

    Tag = sa.Table("tags", metadata, autoload_with=connection)
    Subject = sa.Table("subjects", metadata, autoload_with=connection)

    connection.execute(
        sa.insert(Subject).from_select(
            [Subject.c.id, Subject.c.name, Subject.c.tutor_id],
            sa.select(Tag.c.id, Tag.c.name, Tag.c.tutor_id).where(
                Tag.c.kind == sa.literal_column("'SUBJECT'::tagkind")
            ),
        )
    )
    connection.execute(
        sa.text(
            "SELECT setval("
            "pg_get_serial_sequence('xi_back_2.subjects', 'id'), "
            "COALESCE((SELECT MAX(id) FROM xi_back_2.subjects), 1), "
            "(SELECT MAX(id) FROM xi_back_2.subjects) IS NOT NULL"
            ")"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_index_tags_kind_tutor_id_name", table_name="tags", schema="xi_back_2"
    )
    op.drop_table("tags", schema="xi_back_2")
    # ### end Alembic commands ###

    sa.Enum(name="tagkind").drop(bind=connection)
