"""material_tags

Revision ID: 083
Revises: 082
Create Date: 2026-08-30 20:07:03.632377

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "083"
down_revision: Union[str, None] = "082"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_tags",
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["xi_back_2.materials.id"],
            name=op.f("fk_material_tags_material_id_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("material_id", "tag_id", name=op.f("pk_material_tags")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("material_tags", schema="xi_back_2")
    # ### end Alembic commands ###
