"""coloured_tags

Revision ID: 084
Revises: 083
Create Date: 2026-08-31 17:47:41.064876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "084"
down_revision: Union[str, None] = "083"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_enum = sa.Enum(
    "RED",
    "ORANGE",
    "YELLOW",
    "GREEN",
    "TEAL",
    "BLUE",
    "INDIGO",
    "PURPLE",
    "PINK",
    "BROWN",
    name="tagcolor",
)


def upgrade() -> None:
    conn = op.get_bind()
    new_enum.create(bind=conn)

    op.add_column(
        "tags",
        sa.Column("color", new_enum, nullable=True),
        schema="xi_back_2",
    )

    metadata = sa.MetaData(schema="xi_back_2")
    Tag = sa.Table("tags", metadata, autoload_with=conn)

    conn.execute(
        sa.update(Tag).values(
            color=sa.literal_column(
                "(enum_range(NULL::tagcolor))"
                "[floor(random() * cardinality(enum_range(NULL::tagcolor))) + 1]"
            )
        )
    )

    op.alter_column(
        "tags",
        column_name="color",
        nullable=False,
        schema="xi_back_2",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "color", schema="xi_back_2")
    # ### end Alembic commands ###

    conn = op.get_bind()
    new_enum.drop(bind=conn)
