"""classroom_files

Revision ID: 085
Revises: 084
Create Date: 2026-08-31 04:54:24.829328

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "085"
down_revision: Union[str, None] = "084"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classroom_files",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["xi_back_2.files.id"],
            name=op.f("fk_classroom_files_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "file_id", "classroom_id", name=op.f("pk_classroom_files")
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_classroom_files_classroom_id"),
        "classroom_files",
        ["classroom_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_classroom_files_classroom_id"),
        table_name="classroom_files",
        schema="xi_back_2",
    )
    op.drop_table("classroom_files", schema="xi_back_2")
    # ### end Alembic commands ###
