"""drop_ydoc_content_column

Revision ID: 088
Revises: 087
Create Date: 2026-09-14 01:45:16.622006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "088"
down_revision: Union[str, None] = "087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ydocs", "content", schema="xi_back_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ydocs",
        sa.Column("content", postgresql.BYTEA(), autoincrement=False, nullable=True),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###
