"""promocode_terms

Revision ID: 090
Revises: 089
Create Date: 2026-09-21 08:39:58.673634

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "090"
down_revision: Union[str, None] = "089"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promocodes",
        sa.Column(
            "subscription_days",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        schema="xi_back_2",
    )
    op.add_column(
        "promocodes",
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        schema="xi_back_2",
    )
    op.add_column(
        "promocodes",
        sa.Column(
            "usage_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        schema="xi_back_2",
    )
    op.add_column(
        "promocodes",
        sa.Column("max_account_age_days", sa.Integer(), nullable=True),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promocodes", "max_account_age_days", schema="xi_back_2")
    op.drop_column("promocodes", "usage_count", schema="xi_back_2")
    op.drop_column("promocodes", "usage_limit", schema="xi_back_2")
    op.drop_column("promocodes", "subscription_days", schema="xi_back_2")
    # ### end Alembic commands ###
