"""subscriptions

Revision ID: 091
Revises: 090
Create Date: 2026-09-21 19:04:26.044444

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "091"
down_revision: Union[str, None] = "090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "plan_kind", sa.Enum("PRO", name="subscriptionplankind"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        schema="xi_back_2",
    )
    op.create_index(
        "index_subscriptions_user_id_ends_at",
        "subscriptions",
        ["user_id", "ends_at"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_subscriptions_user_id_ends_at",
        table_name="subscriptions",
        schema="xi_back_2",
    )
    op.drop_table("subscriptions", schema="xi_back_2")
    # ### end Alembic commands ###

    sa.Enum(name="subscriptionplankind").drop(bind=op.get_bind())
