"""payments

Revision ID: 092
Revises: 091
Create Date: 2026-09-21 22:00:05.412859

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "092"
down_revision: Union[str, None] = "091"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount_roubles", sa.Integer(), nullable=False),
        sa.Column("subscription_days", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_payments_provider_payment_id"),
        "payments",
        ["provider_payment_id"],
        unique=True,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_payments_user_id"),
        "payments",
        ["user_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_payments_user_id"), table_name="payments", schema="xi_back_2"
    )
    op.drop_index(
        op.f("ix_xi_back_2_payments_provider_payment_id"),
        table_name="payments",
        schema="xi_back_2",
    )
    op.drop_table("payments", schema="xi_back_2")
    # ### end Alembic commands ###
