"""one_subscription_per_user

Revision ID: 093
Revises: 092
Create Date: 2026-09-23 01:45:07.559934

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "093"
down_revision: Union[str, None] = "092"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # no subscriptions on prod yet, so it's fine to just delete data
    op.execute("TRUNCATE TABLE xi_back_2.subscriptions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_subscriptions_user_id_ends_at",
        table_name="subscriptions",
        schema="xi_back_2",
    )
    op.drop_column("subscriptions", "created_at", schema="xi_back_2")
    op.drop_column("subscriptions", "id", schema="xi_back_2")
    # ### end Alembic commands ###

    op.create_primary_key(
        "pk_subscriptions",
        "subscriptions",
        ["user_id"],
        schema="xi_back_2",
    )


def downgrade() -> None:
    op.execute("TRUNCATE TABLE xi_back_2.subscriptions")

    op.drop_constraint(
        "pk_subscriptions",
        "subscriptions",
        type_="primary",
        schema="xi_back_2",
    )
    op.execute("ALTER TABLE xi_back_2.subscriptions ADD COLUMN id SERIAL NOT NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        schema="xi_back_2",
    )
    op.create_index(
        "index_subscriptions_user_id_ends_at",
        "subscriptions",
        ["user_id", "ends_at"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###

    op.create_primary_key(
        "pk_subscriptions",
        "subscriptions",
        ["id"],
        schema="xi_back_2",
    )
