"""promocode_redemptions

Revision ID: 095
Revises: 094
Create Date: 2026-09-28 06:53:37.157101

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "095"
down_revision: Union[str, None] = "094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocode_redemptions",
        sa.Column("promocode_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["promocode_id"],
            ["xi_back_2.promocodes.id"],
            name=op.f("fk_promocode_redemptions_promocode_id_promocodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "promocode_id", "user_id", name=op.f("pk_promocode_redemptions")
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_promocode_redemptions_user_id"),
        "promocode_redemptions",
        ["user_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_promocode_redemptions_user_id"),
        table_name="promocode_redemptions",
        schema="xi_back_2",
    )
    op.drop_table("promocode_redemptions", schema="xi_back_2")
    # ### end Alembic commands ###
