"""auto_renewals

Revision ID: 095
Revises: 094
Create Date: 2026-09-28 05:20:57.042024

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "095"
down_revision: Union[str, None] = "094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_renewals",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider_payment_method_id", sa.String(length=50), nullable=False),
        sa.Column(
            "renewal_period",
            sa.Enum("MONTHLY", "YEARLY", name="subscriptionperiod"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_auto_renewals")),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auto_renewals", schema="xi_back_2")
    # ### end Alembic commands ###

    sa.Enum(name="subscriptionperiod").drop(bind=op.get_bind())
