"""user_flag_kinds

Revision ID: 096
Revises: 095
Create Date: 2026-09-28 08:23:12.526235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "096"
down_revision: Union[str, None] = "095"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_flag_kinds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("default_value", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_flag_kinds")),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_user_flag_kinds_key"),
        "user_flag_kinds",
        ["key"],
        unique=True,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_user_flag_kinds_key"),
        table_name="user_flag_kinds",
        schema="xi_back_2",
    )
    op.drop_table("user_flag_kinds", schema="xi_back_2")
    # ### end Alembic commands ###
