"""user_flags

Revision ID: 097
Revises: 096
Create Date: 2026-09-28 12:10:09.587796

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "097"
down_revision: Union[str, None] = "096"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_flags",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_flag_kind_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_flag_kind_id"],
            ["xi_back_2.user_flag_kinds.id"],
            name=op.f("fk_user_flags_user_flag_kind_id_user_flag_kinds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["xi_back_2.users.id"],
            name=op.f("fk_user_flags_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "user_flag_kind_id", name=op.f("pk_user_flags")
        ),
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_user_flags_user_flag_kind_id"),
        "user_flags",
        ["user_flag_kind_id"],
        unique=False,
        schema="xi_back_2",
    )
    op.create_index(
        op.f("ix_xi_back_2_user_flags_user_id"),
        "user_flags",
        ["user_id"],
        unique=False,
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_xi_back_2_user_flags_user_id"),
        table_name="user_flags",
        schema="xi_back_2",
    )
    op.drop_index(
        op.f("ix_xi_back_2_user_flags_user_flag_kind_id"),
        table_name="user_flags",
        schema="xi_back_2",
    )
    op.drop_table("user_flags", schema="xi_back_2")
    # ### end Alembic commands ###
