"""payment_confirmation_url

Revision ID: 098
Revises: 097
Create Date: 2026-10-05 01:44:01.672991

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "098"
down_revision: Union[str, None] = "097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # no payments in prod yet, so it's fine to just delete data
    op.execute("TRUNCATE TABLE xi_back_2.payments")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("confirmation_url", sa.Text(), nullable=False),
        schema="xi_back_2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "confirmation_url", schema="xi_back_2")
    # ### end Alembic commands ###
