name: Main Pipeline

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      base_tag:
        type: string
        required: false
      branch:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
      check_coverage:
        type: boolean
        required: true
      check_migrations:
        type: boolean
        required: true
      enable_deployment:
        type: boolean
        required: true
      is_mainline:
        type: boolean
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      repository_cache_name: back-2
      postgres_schema: ${{ inputs.check_migrations && 'xi_back_2' || '' }}

    services:
      db:
        image: postgres:16.1-alpine
        env:
          PGUSER: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load Cached Venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4.2.0
        with:
          path: .venv
          key: ${{ env.repository_cache_name }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ env.repository_cache_name }}-venv-

      - name: Load Cached Pre-commit
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pre-commit
          key: ${{ env.repository_cache_name }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ env.repository_cache_name }}-pre-commit-

      - name: Load Mypy Cache
        uses: actions/cache@v4.2.0
        with:
          path: .mypy_cache
          key: ${{ env.repository_cache_name }}-mypy

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Activate virtualenv
        id: venv
        run: |
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Setup database for migrationless tests
        if: ${{ !inputs.check_migrations }}
        run: |
          source .venv/bin/activate
          python -m app.setup_ci

      - name: Upgrade database to latest migration
        if: ${{ inputs.check_migrations }}
        run: alembic upgrade head

      - name: Check that database is up to date with code
        if: ${{ inputs.check_migrations }}
        run: |
          alembic revision --autogenerate -m 'test' --rev-id 0
          lines=$(cat ./migrations/versions/0_test.py | wc -l)
          echo $lines
          if [ $lines -ne 30 ]; then
            exit 1
          fi

      - name: Run pytest
        run: pytest tests -p no:cacheprovider --cov=app ${{ !inputs.check_coverage && '--cov-fail-under=0' || ''}}
        env:
          postgres_automigrate: false

      - name: Run pre-commit for all files
        if: ${{ success() || (failure() && steps.venv.conclusion == 'success') }}
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  build:
    needs: prepare
    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: ${{ inputs.tag }}
      base-tag: ${{ inputs.base_tag }}
    secrets: inherit

  deploy:
    needs: build
    if: ${{ inputs.enable_deployment }}

    strategy:
      fail-fast: false
      matrix:
        environment:
          - staging
          - production

    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    env:
      pull_image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USERNAME }}:${{ inputs.tag }}
      deploy_image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USERNAME }}:${{ secrets.DEPLOY_TAG }}

    steps:
      - name: Run SSH commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |-
            cd ~/xieffect-core
            docker pull ${{ env.pull_image }}
            docker tag ${{ env.pull_image }} ${{ env.deploy_image }}
            ${{ inputs.is_mainline }} || docker tag ${{ env.deploy_image }} ${{ env.deploy_image }}-backup
            docker rmi ${{ env.pull_image }}
            docker compose run --rm ${{ vars.compose_migration_service }}
            docker compose up -d ${{ vars.compose_app_service }}
            ${{ !inputs.is_mainline }} || docker compose exec ${{ vars.compose_app_service }} alembic heads | cut -d ' ' --fields=1 > ${{ vars.version_filename }}
          script_stop: true

      - name: Report status to discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |-
            :white_check_mark: Service xi.back-2 successfully deployed
            Commit: `${{ inputs.commit_sha }}`
            Branch: `${{ inputs.branch }}`
            Issuer: `${{ github.triggering_actor }}`

      - name: Report failure to discord
        if: ${{ failure() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |-
            :red_circle: [Service xi.back-2 failed to deploy](<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>)
            Commit: `${{ inputs.commit_sha }}`
            Branch: `${{ inputs.branch }}`
            Issuer: `${{ github.triggering_actor }}`
